#!/usr/bin/env bash
# SSH configuration

Host *
    passwordAuthentication no
    IdentityFile -/.ssh/school
    sendEnv LANO LC_*
    FlashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
